{
 "testCollection": {
  "name": "15.10.2",
  "numTests": 5,
  "tests": [
   {
    "id": "15.10.2.15-3-1",
    "path": "TestCases/chapter15/15.10/15.10.2/15.10.2.15-3-1.js",
    "description": "Pattern - SyntaxError was thrown when 'A' does not contain exactly one character (15.10.2.5 step 3)",
    "test": "assertTrue((function testcase() {\n        try {\n            var regExp = new RegExp(\"^[/w-c]$\");\n\n            return false;\n        } catch (e) {\n            return e instanceof SyntaxError;\n        }\n    }).call(this));\n"
   },
   {
    "id": "15.10.2.15-3-2",
    "path": "TestCases/chapter15/15.10/15.10.2/15.10.2.15-3-2.js",
    "description": "Pattern - SyntaxError was thrown when 'B' does not contain exactly one character (15.10.2.5 step 3)",
    "test": "assertTrue((function testcase() {\n        try {\n            var regExp = new RegExp(\"^[a-/w]$\");\n\n            return false;\n        } catch (e) {\n            return e instanceof SyntaxError;\n        }\n    }).call(this));\n"
   },
   {
    "id": "15.10.2.15-6-1",
    "path": "TestCases/chapter15/15.10/15.10.2/15.10.2.15-6-1.js",
    "description": "Pattern - SyntaxError was thrown when one character in CharSet 'A' greater than one character in CharSet 'B' (15.10.2.15 CharacterRange step 6)",
    "test": "assertTrue((function testcase() {\n        try {\n            var regExp = new RegExp(\"^[z-a]$\");\n\n            return false;\n        } catch (e) {\n            return e instanceof SyntaxError;\n        }\n    }).call(this));\n"
   },
   {
    "id": "15.10.2.2-1",
    "path": "TestCases/chapter15/15.10/15.10.2/15.10.2.2-1.js",
    "description": "Pattern - SyntaxError was thrown when compile a pattern",
    "test": "assertTrue((function testcase() {\n        try {\n            var regExp = new RegExp(\"\\\\\");\n\n            return false;\n        } catch (e) {\n            return e instanceof SyntaxError;\n        }\n    }).call(this));\n"
   },
   {
    "id": "15.10.2.5-3-1",
    "path": "TestCases/chapter15/15.10/15.10.2/15.10.2.5-3-1.js",
    "description": "Term - SyntaxError was thrown when max is finite and less than min (15.10.2.5 step 3)",
    "test": "assertTrue((function testcase() {\n        try {\n            var regExp = new RegExp(\"0{2,1}\");\n\n            return false;\n        } catch (e) {\n            return e instanceof SyntaxError;\n        }\n    }).call(this));\n"
   }
  ]
 }
}
